FROM node:20-alpine AS base
WORKDIR /app

COPY web/package*.json ./
RUN npm ci

COPY web/ .
COPY shared /shared
COPY design /design

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package*.json ./
COPY --from=base /app/.next ./.next
COPY --from=base /app/public ./public
COPY web/next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npm", "run", "start"]
