FROM node:20-alpine AS base
WORKDIR /app

COPY backend/package*.json ./
COPY backend/prisma ./prisma
RUN npm ci
COPY backend/tsconfig*.json ./
COPY backend/src ./src
COPY backend/shared ./shared
COPY backend/scripts ./scripts

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/dist ./dist
COPY backend/package*.json ./
COPY backend/prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/main.js"]
