import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  RefreshControl,
  Share,
} from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { GlassCard } from '../../../components/ui/GlassCard';
import { Icon } from '../../../components/ui';
import { InsightCard } from '../../../components/smart-scout';
import { colors, spacing, typography, radius } from '../../../design/theme';
import { smartScoutApi } from '../../../services/api/smart-scout';
import { playersApi } from '../../../services/api/players';
import type { PlayerInsights } from '../../../types/smart-scout';
import type { Player } from '../../../types';
import Toast from 'react-native-toast-message';

export const InsightsTab: React.FC = () => {
  const [players, setPlayers] = useState<Player[]>([]);
  const [selectedPlayerId, setSelectedPlayerId] = useState<string>('');
  const [insights, setInsights] = useState<PlayerInsights | null>(null);
  const [isLoadingPlayers, setIsLoadingPlayers] = useState(false);
  const [isLoadingInsights, setIsLoadingInsights] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);

  React.useEffect(() => {
    loadPlayers();
  }, []);

  const loadPlayers = async () => {
    try {
      setIsLoadingPlayers(true);
      const data = await playersApi.getAllPlayers({ limit: 100 });
      setPlayers(data);
      if (data.length > 0 && !selectedPlayerId) {
        setSelectedPlayerId(data[0].id);
      }
    } catch (error) {
      console.error('Error loading players:', error);
      Toast.show({
        type: 'error',
        text1: 'Error',
        text2: 'Failed to load players',
      });
    } finally {
      setIsLoadingPlayers(false);
    }
  };

  const handleGenerateInsights = async () => {
    if (!selectedPlayerId) {
      Toast.show({
        type: 'warning',
        text1: 'No Player Selected',
        text2: 'Please select a player first',
      });
      return;
    }

    try {
      setIsLoadingInsights(true);
      const data = await smartScoutApi.getInsights(selectedPlayerId);
      setInsights(data);
      Toast.show({
        type: 'success',
        text1: 'Insights Generated',
        text2: 'AI analysis complete',
      });
    } catch (error) {
      console.error('Error generating insights:', error);
      Toast.show({
        type: 'error',
        text1: 'Error',
        text2: 'Failed to generate insights',
      });
    } finally {
      setIsLoadingInsights(false);
    }
  };

  const handleRefresh = async () => {
    if (!selectedPlayerId || !insights) return;

    try {
      setIsRefreshing(true);
      const data = await smartScoutApi.getInsights(selectedPlayerId);
      setInsights(data);
      Toast.show({
        type: 'success',
        text1: 'Refreshed',
        text2: 'Insights updated',
      });
    } catch (error) {
      console.error('Error refreshing insights:', error);
      Toast.show({
        type: 'error',
        text1: 'Error',
        text2: 'Failed to refresh insights',
      });
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleShareInsights = async () => {
    if (!insights) return;

    try {
      const message = `
SmartScout AI Insights - ${insights.playerName}

${insights.summary}

Average Ratings:
- Technical: ${Math.round(insights.avgRatings.technical)}
- Tactical: ${Math.round(insights.avgRatings.tactical)}
- Physical: ${Math.round(insights.avgRatings.physical)}
- Mental: ${Math.round(insights.avgRatings.mental)}

Scout Consensus: ${Math.round(insights.consensus.agreementPercentage)}% agreement from ${insights.consensus.totalReports} reports

Generated by ARCANE SmartScout AI
      `.trim();

      await Share.share({
        message,
        title: `Player Insights - ${insights.playerName}`,
      });
    } catch (error) {
      console.error('Error sharing insights:', error);
    }
  };

  const getPlayerDisplayName = (player: Player) => {
    return `${player.user.firstName} ${player.user.lastName} (${player.position})`;
  };

  const renderEmptyState = () => {
    if (isLoadingPlayers) {
      return (
        <View style={styles.emptyState}>
          <ActivityIndicator size="large" color={colors.brand.primary} />
          <Text style={styles.emptyText}>Loading players...</Text>
        </View>
      );
    }

    if (players.length === 0) {
      return (
        <View style={styles.emptyState}>
          <Icon name="peopleOutline" size={64} color={colors.text.secondary} />
          <Text style={styles.emptyText}>No players available</Text>
          <Text style={styles.emptySubtext}>
            Add players to generate insights
          </Text>
        </View>
      );
    }

    if (!insights) {
      return (
        <View style={styles.emptyState}>
          <Icon name="analytics" size={64} color={colors.text.secondary} />
          <Text style={styles.emptyText}>No insights generated yet</Text>
          <Text style={styles.emptySubtext}>
            Select a player and tap "Generate Insights"
          </Text>
        </View>
      );
    }

    return null;
  };

  return (
    <View style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={
          insights ? (
            <RefreshControl
              refreshing={isRefreshing}
              onRefresh={handleRefresh}
              tintColor={colors.brand.primary}
            />
          ) : undefined
        }
      >
        {/* Player Selection */}
        <GlassCard variant="bordered" style={styles.card}>
          <Text style={styles.sectionTitle}>Select Player</Text>

          {isLoadingPlayers ? (
            <ActivityIndicator size="small" color={colors.brand.primary} />
          ) : (
            <View style={styles.pickerContainer}>
              <Picker
                selectedValue={selectedPlayerId}
                onValueChange={(value) => {
                  setSelectedPlayerId(value);
                  setInsights(null); // Clear previous insights
                }}
                style={styles.picker}
                dropdownIconColor={colors.text.primary}
                enabled={players.length > 0}
              >
                {players.map((player) => (
                  <Picker.Item
                    key={player.id}
                    label={getPlayerDisplayName(player)}
                    value={player.id}
                  />
                ))}
              </Picker>
            </View>
          )}

          {/* Generate Button */}
          <TouchableOpacity
            style={[
              styles.generateButton,
              (isLoadingInsights || !selectedPlayerId) && styles.generateButtonDisabled,
            ]}
            onPress={handleGenerateInsights}
            disabled={isLoadingInsights || !selectedPlayerId}
          >
            {isLoadingInsights ? (
              <ActivityIndicator color={colors.background.primary} />
            ) : (
              <>
                <Icon name="sparkles" size={20} color={colors.background.primary} />
                <Text style={styles.generateButtonText}>Generate AI Insights</Text>
              </>
            )}
          </TouchableOpacity>
        </GlassCard>

        {/* Insights Display */}
        {insights ? (
          <>
            {/* Share Button */}
            <TouchableOpacity
              style={styles.shareButton}
              onPress={handleShareInsights}
            >
              <Icon name="shareOutline" size={20} color={colors.brand.primary} />
              <Text style={styles.shareButtonText}>Share Insights</Text>
            </TouchableOpacity>

            <InsightCard insights={insights} />
          </>
        ) : (
          renderEmptyState()
        )}

        {/* Info Box */}
        {!insights && players.length > 0 && (
          <View style={styles.infoBox}>
            <Icon name="informationCircle" size={24} color={colors.status.info} />
            <Text style={styles.infoText}>
              SmartScout AI analyzes all scouting reports for the selected player to provide
              comprehensive insights, trends, and consensus ratings.
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.md,
  },
  card: {
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.sizes.xl,
    fontWeight: 'bold',
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  pickerContainer: {
    backgroundColor: colors.surface.glassLight,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.background.tertiary,
    overflow: 'hidden',
    marginBottom: spacing.md,
  },
  picker: {
    color: colors.text.primary,
    height: 50,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand.primary,
    paddingVertical: spacing.md,
    borderRadius: radius.lg,
    gap: spacing.sm,
  },
  generateButtonDisabled: {
    opacity: 0.6,
  },
  generateButtonText: {
    fontSize: typography.sizes.lg,
    fontWeight: 'bold',
    color: colors.background.primary,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    marginBottom: spacing.md,
  },
  shareButtonText: {
    fontSize: typography.sizes.base,
    fontWeight: '600',
    color: colors.brand.primary,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl * 2,
  },
  emptyText: {
    fontSize: typography.sizes.lg,
    fontWeight: 'bold',
    color: colors.text.primary,
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  emptySubtext: {
    fontSize: typography.sizes.base,
    color: colors.text.secondary,
    textAlign: 'center',
    paddingHorizontal: spacing.xl,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: colors.status.info + '20',
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.status.info + '40',
    marginTop: spacing.md,
  },
  infoText: {
    flex: 1,
    fontSize: typography.sizes.base,
    color: colors.text.primary,
    lineHeight: 20,
  },
});
