'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Save, RefreshCw, Trash2, Edit3, AlertTriangle, User, MapPin } from 'lucide-react';
import { GeneratedReport } from '@/types/auto-scout';
import { QualityScoreBadge } from './QualityScoreBadge';
import { ReportSectionCard } from './ReportSectionCard';

interface GeneratedReportPreviewProps {
  report: GeneratedReport;
  onSave: () => void;
  onRegenerate: () => void;
  onDiscard: () => void;
}

export function GeneratedReportPreview({
  report,
  onSave,
  onRegenerate,
  onDiscard,
}: GeneratedReportPreviewProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedSummary, setEditedSummary] = useState(report.summary);

  const handleSave = () => {
    // In a real implementation, this would update the report with edited content
    onSave();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-3 mb-2">
            <h2 className="text-3xl font-bold text-white">
              {report.playerName}
            </h2>
            <span className="px-3 py-1 rounded-full bg-[#e6ff3c]/20 border border-[#e6ff3c]/30 text-[#e6ff3c] text-sm font-semibold">
              {report.position}
            </span>
          </div>

          <div className="flex items-center gap-4 text-sm text-gray-400">
            {report.age && (
              <span className="flex items-center gap-1">
                <User className="w-4 h-4" />
                {report.age} years old
              </span>
            )}
            {report.club && (
              <span className="flex items-center gap-1">
                <MapPin className="w-4 h-4" />
                {report.club}
              </span>
            )}
            <span>•</span>
            <span className="text-purple-400">
              Generated by GPT-4
            </span>
          </div>
        </div>

        {/* Quality score */}
        <QualityScoreBadge qualityScore={report.qualityScore} size="md" />
      </div>

      {/* Low quality warning */}
      {report.qualityScore.grade === 'C' || report.qualityScore.grade === 'D' && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30"
        >
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <h4 className="text-sm font-semibold text-amber-400 mb-1">
                Low Quality Score
              </h4>
              <p className="text-xs text-gray-300">
                This report has a quality score of {report.qualityScore.grade}. Consider regenerating
                or adding more context to improve the analysis quality.
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Summary */}
      <div className="p-6 rounded-xl bg-gradient-to-br from-[#e6ff3c]/10 to-purple-500/10 border border-white/10">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-lg font-bold text-white">
            Executive Summary
          </h3>
          <button
            onClick={() => setIsEditing(!isEditing)}
            className="p-2 rounded-lg hover:bg-white/10 transition-colors"
          >
            <Edit3 className="w-4 h-4 text-gray-400" />
          </button>
        </div>

        {isEditing ? (
          <textarea
            value={editedSummary}
            onChange={(e) => setEditedSummary(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-black/40 border border-white/10 text-white focus:outline-none focus:border-[#e6ff3c] transition-colors resize-none"
            rows={6}
          />
        ) : (
          <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
            {editedSummary}
          </p>
        )}
      </div>

      {/* Report sections */}
      <div className="space-y-4">
        <h3 className="text-xl font-bold text-white">
          Detailed Analysis
        </h3>

        <ReportSectionCard
          title="Technical Skills"
          section={report.technicalSkills}
          defaultExpanded={true}
        />

        <ReportSectionCard
          title="Tactical Awareness"
          section={report.tacticalAwareness}
        />

        <ReportSectionCard
          title="Physical Attributes"
          section={report.physicalAttributes}
        />

        <ReportSectionCard
          title="Mental Attributes"
          section={report.mentalAttributes}
        />
      </div>

      {/* Overall rating and potential */}
      <div className="grid grid-cols-2 gap-4">
        <div className="p-6 rounded-xl bg-black/40 border border-white/10">
          <h4 className="text-sm font-semibold text-gray-400 mb-2">
            Overall Rating
          </h4>
          <p className="text-4xl font-bold text-[#e6ff3c]">
            {report.overallRating.toFixed(1)}/10
          </p>
        </div>

        <div className="p-6 rounded-xl bg-black/40 border border-white/10">
          <h4 className="text-sm font-semibold text-gray-400 mb-2">
            Potential
          </h4>
          <p className="text-2xl font-bold text-white">
            {report.potential}
          </p>
        </div>
      </div>

      {/* Recommendations */}
      {report.recommendations && report.recommendations.length > 0 && (
        <div className="p-6 rounded-xl bg-blue-500/10 border border-blue-500/30">
          <h4 className="text-lg font-bold text-white mb-3">
            Recommendations
          </h4>
          <ul className="space-y-2">
            {report.recommendations.map((rec, index) => (
              <li key={index} className="flex items-start gap-2 text-sm text-gray-300">
                <span className="text-blue-400 mt-1">•</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Comparable players */}
      {report.comparablePlayers && report.comparablePlayers.length > 0 && (
        <div className="p-6 rounded-xl bg-purple-500/10 border border-purple-500/30">
          <h4 className="text-lg font-bold text-white mb-3">
            Comparable Players
          </h4>
          <div className="flex flex-wrap gap-2">
            {report.comparablePlayers.map((player, index) => (
              <span
                key={index}
                className="px-3 py-1 rounded-full bg-white/10 border border-white/20 text-sm text-white"
              >
                {player}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Metadata */}
      <div className="p-4 rounded-xl bg-white/5 border border-white/10 text-xs text-gray-400">
        <div className="flex flex-wrap gap-4">
          <span>Generated: {new Date(report.generatedAt).toLocaleString()}</span>
          <span>•</span>
          <span>Model: {report.model}</span>
          {report.tokensUsed && (
            <>
              <span>•</span>
              <span>Tokens: {report.tokensUsed}</span>
            </>
          )}
          {report.estimatedCost && (
            <>
              <span>•</span>
              <span>Cost: ${report.estimatedCost.toFixed(4)}</span>
            </>
          )}
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex gap-4">
        <button
          onClick={handleSave}
          className="flex-1 py-4 rounded-xl bg-[#e6ff3c] text-black font-bold hover:bg-[#d8f14e] transition-colors flex items-center justify-center gap-2"
        >
          <Save className="w-5 h-5" />
          Save as Official Report
        </button>

        <button
          onClick={onRegenerate}
          className="px-6 py-4 rounded-xl bg-white/10 border border-white/20 text-white font-semibold hover:bg-white/20 transition-colors flex items-center justify-center gap-2"
        >
          <RefreshCw className="w-5 h-5" />
          Regenerate
        </button>

        <button
          onClick={onDiscard}
          className="px-6 py-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 font-semibold hover:bg-red-500/20 transition-colors flex items-center justify-center gap-2"
        >
          <Trash2 className="w-5 h-5" />
          Discard
        </button>
      </div>
    </div>
  );
}
