import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Share,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import * as Haptics from 'expo-haptics';
import { GlassCard } from '../../components/ui/GlassCard';
import {
  ValuationCard,
  ConfidenceIndicator,
  FactorBar,
  ComparablePlayerCard,
  TrendChart,
} from '../../components/market-value';
import { Icon } from '../../components/ui';
import { colors, spacing, typography, radius } from '../../design/theme';
import { marketValueApi } from '../../services/api/market-value';
import api from '../../services/api';
import type { AppStackParamList } from '../../types/navigation';
import type { PlayerValuation, ValuationTrend } from '../../types/market-value';

type Props = NativeStackScreenProps<AppStackParamList, 'MarketValueDetail'>;

export const MarketValueDetailScreen: React.FC<Props> = ({ navigation, route }) => {
  const { playerId } = route.params || {};
  const [loading, setLoading] = useState(true);
  const [valuation, setValuation] = useState<PlayerValuation | null>(null);
  const [trend, setTrend] = useState<ValuationTrend | null>(null);
  const [playerData, setPlayerData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!playerId || playerId.length < 10) {
      setError('Invalid player ID');
      setLoading(false);
      return;
    }
    fetchData();
  }, [playerId]);

  const fetchData = async () => {
    try {
      setLoading(true);
      setError(null);

      const [valuationData, trendData] = await Promise.all([
        marketValueApi.getValuation(playerId),
        marketValueApi.getTrend(playerId).catch(() => null), // Trend might not be available
      ]);

      setValuation(valuationData);
      setTrend(trendData);

      // Try to fetch player details
      try {
        const player = await api.getPlayer(playerId);
        setPlayerData(player);
      } catch (err) {
        console.log('Could not fetch player details');
      }
    } catch (err: any) {
      console.error('Failed to fetch data:', err);
      setError(
        err.response?.status === 404
          ? 'Player not found'
          : err.response?.status === 503
          ? 'AI service is currently unavailable'
          : 'Failed to fetch data. Please try again.'
      );
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = useCallback(async () => {
    if (!valuation) return;

    try {
      const playerName = playerData?.name || valuation.playerName || 'Player';
      const message = `${playerName} Market Valuation:\n\nEstimated Value: €${valuation.estimatedValue.toFixed(
        1
      )}M\nConfidence: ${Math.round(
        valuation.confidenceScore * 100
      )}%\nRange: €${valuation.confidenceInterval.low.toFixed(
        1
      )}M - €${valuation.confidenceInterval.high.toFixed(
        1
      )}M\n\nGenerated by ARCANE AI`;

      await Share.share({
        message,
        title: `${playerName} - Market Value`,
      });

      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (err) {
      console.error('Failed to share:', err);
    }
  }, [valuation, playerData]);

  if (loading) {
    return (
      <SafeAreaView style={styles.container} edges={['top']}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
            <Icon name="arrowBack" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Valuation Details</Text>
          <View style={styles.placeholder} />
        </View>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.brand.primary} />
          <Text style={styles.loadingText}>Loading valuation data...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (error || !valuation) {
    return (
      <SafeAreaView style={styles.container} edges={['top']}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
            <Icon name="arrowBack" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Valuation Details</Text>
          <View style={styles.placeholder} />
        </View>
        <View style={styles.errorContainer}>
          <Icon name="alertCircle" size={64} color={colors.semantic.error} />
          <Text style={styles.errorText}>{error || 'Failed to load data'}</Text>
          <TouchableOpacity style={styles.retryButton} onPress={fetchData}>
            <Text style={styles.retryText}>Try Again</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const playerName = playerData?.name || valuation.playerName || 'Player';
  const factorEntries = Object.entries(valuation.factors).sort(([, a], [, b]) => b - a);
  const maxFactorValue = Math.max(...factorEntries.map(([, value]) => value));

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Icon name="arrowBack" size={24} color={colors.text.primary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Valuation Details</Text>
        <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
          <Icon name="share" size={24} color={colors.brand.primary} />
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        {/* Player Info */}
        {playerData && (
          <GlassCard variant="elevated" style={styles.playerCard}>
            <View style={styles.playerInfo}>
              <View style={styles.playerAvatar}>
                <Text style={styles.playerAvatarText}>
                  {playerName.charAt(0).toUpperCase()}
                </Text>
              </View>
              <View style={styles.playerDetails}>
                <Text style={styles.playerName}>{playerName}</Text>
                {playerData.position && (
                  <View style={styles.playerMeta}>
                    <Text style={styles.playerMetaText}>{playerData.position}</Text>
                    {playerData.age && (
                      <>
                        <View style={styles.separator} />
                        <Text style={styles.playerMetaText}>{playerData.age} years</Text>
                      </>
                    )}
                  </View>
                )}
              </View>
            </View>
          </GlassCard>
        )}

        {/* Main Valuation */}
        <ValuationCard
          value={valuation.estimatedValue}
          interval={[valuation.confidenceInterval.low, valuation.confidenceInterval.high]}
          confidence={valuation.confidenceScore}
        />

        {/* Historical Trend */}
        {trend && trend.valuations.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionTitle}>Historical Trend</Text>
              <Icon name="trendingUp" size={20} color={colors.brand.primary} />
            </View>
            <TrendChart
              dataPoints={trend.valuations}
              trend={trend.trend}
              changePercentage={trend.changePercent}
            />
          </View>
        )}

        {/* Two Column Layout: Confidence + Top Factor */}
        <View style={styles.twoColumnContainer}>
          <GlassCard variant="elevated" style={styles.smallCard}>
            <ConfidenceIndicator confidence={valuation.confidenceScore} size={100} />
          </GlassCard>

          {factorEntries.length > 0 && (
            <GlassCard variant="elevated" style={styles.smallCard}>
              <View style={styles.topFactorContainer}>
                <Text style={styles.topFactorLabel}>TOP FACTOR</Text>
                <Text style={styles.topFactorName}>
                  {factorEntries[0][0]
                    .split('_')
                    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
                    .join(' ')}
                </Text>
                <Text style={styles.topFactorValue}>{factorEntries[0][1].toFixed(1)}</Text>
              </View>
            </GlassCard>
          )}
        </View>

        {/* All Factors */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Factor Analysis</Text>
            <Icon name="barChart" size={20} color={colors.brand.primary} />
          </View>
          <GlassCard variant="bordered">
            <View style={styles.factorsContainer}>
              {factorEntries.map(([name, value], index) => (
                <FactorBar
                  key={name}
                  name={name}
                  value={value}
                  maxValue={maxFactorValue}
                  index={index}
                />
              ))}
            </View>
          </GlassCard>
        </View>

        {/* Comparable Players */}
        {valuation.comparablePlayers.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionTitle}>Similar Players</Text>
              <Icon name="people" size={20} color={colors.brand.primary} />
            </View>
            {valuation.comparablePlayers.map((player, index) => (
              <ComparablePlayerCard key={index} player={player} />
            ))}
          </View>
        )}

        {/* Model Info */}
        <GlassCard variant="bordered" style={styles.infoCard}>
          <View style={styles.infoRow}>
            <Icon name="informationCircle" size={20} color={colors.text.secondary} />
            <View style={styles.infoContent}>
              <Text style={styles.infoLabel}>Model Version</Text>
              <Text style={styles.infoValue}>{valuation.modelVersion}</Text>
            </View>
          </View>
          <View style={styles.infoDivider} />
          <View style={styles.infoRow}>
            <Icon name="time" size={20} color={colors.text.secondary} />
            <View style={styles.infoContent}>
              <Text style={styles.infoLabel}>Generated</Text>
              <Text style={styles.infoValue}>
                {new Date(valuation.timestamp).toLocaleString()}
              </Text>
            </View>
          </View>
        </GlassCard>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.background.tertiary,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: typography.sizes.xl,
    fontWeight: 'bold',
    color: colors.text.primary,
  },
  placeholder: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  loadingText: {
    marginTop: spacing.lg,
    fontSize: typography.sizes.base,
    color: colors.text.secondary,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  errorText: {
    fontSize: typography.sizes.lg,
    color: colors.semantic.error,
    textAlign: 'center',
    marginTop: spacing.lg,
    marginBottom: spacing.xl,
  },
  retryButton: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface.glassLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.brand.primary,
  },
  retryText: {
    fontSize: typography.sizes.base,
    fontWeight: '600',
    color: colors.brand.primary,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: spacing.md,
  },
  playerCard: {
    marginBottom: spacing.lg,
  },
  playerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
  },
  playerAvatar: {
    width: 64,
    height: 64,
    borderRadius: radius.lg,
    backgroundColor: colors.surface.glassLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.lg,
    borderWidth: 2,
    borderColor: colors.brand.primary,
  },
  playerAvatarText: {
    fontSize: typography.sizes.h2,
    fontWeight: 'bold',
    color: colors.brand.primary,
  },
  playerDetails: {
    flex: 1,
  },
  playerName: {
    fontSize: typography.sizes.h3,
    fontWeight: 'bold',
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  playerMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  playerMetaText: {
    fontSize: typography.sizes.base,
    color: colors.text.secondary,
  },
  separator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.text.secondary,
    marginHorizontal: spacing.sm,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.sizes.xl,
    fontWeight: 'bold',
    color: colors.text.primary,
  },
  twoColumnContainer: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  smallCard: {
    flex: 1,
    padding: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topFactorContainer: {
    alignItems: 'center',
  },
  topFactorLabel: {
    fontSize: typography.sizes.xs,
    fontWeight: '600',
    color: colors.text.secondary,
    letterSpacing: 1,
    marginBottom: spacing.sm,
  },
  topFactorName: {
    fontSize: typography.sizes.base,
    fontWeight: '600',
    color: colors.text.primary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  topFactorValue: {
    fontSize: typography.sizes.h2,
    fontWeight: 'bold',
    color: colors.brand.primary,
  },
  factorsContainer: {
    padding: spacing.md,
  },
  infoCard: {
    marginBottom: spacing.lg,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    gap: spacing.md,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: typography.sizes.sm,
    color: colors.text.secondary,
    marginBottom: spacing.xs / 2,
  },
  infoValue: {
    fontSize: typography.sizes.base,
    fontWeight: '600',
    color: colors.text.primary,
  },
  infoDivider: {
    height: 1,
    backgroundColor: colors.surface.border,
    marginHorizontal: spacing.md,
  },
});
